version: '3.8'

services:
  frontend:
    image: insurance-frontend:latest
    pull_policy: never
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - insurance-network
    restart: unless-stopped


  backend:
    image: flaskback-backend:latest
    pull_policy: never
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TINYLLAMA_SERVICE_URL=http://tinyllama:8000
    depends_on:
      - tinyllama
    networks:
      - insurance-network
    restart: unless-stopped


  tinyllama:
    image: tinyllama-service:latest
    pull_policy: never
    ports:
      - "8000:8000"
    networks:
      - insurance-network
    restart: unless-stopped

networks:
  insurance-network:
    driver: bridge

volumes:

  backend_data: 